name: "simulaPellin"
title: "Simulador Pellin"
type: inverse
homeassistant:
entity_picture: /img/logo.png
left:
  - text: "El modelo"
    href: ./docs.html
  - text: "Simular"
    href: ./simular.html    
  - text: "Equipo"
    href: ./team.html
  - text: "Publicaciones"
    href: ./pubs.html    
  - text: "Contacto"
    href: ./contact.html
  - text: "Actualizaciones"
    href: ./updates.html    
right:
  - icon: fa-home fa-lg
    href: ./index.html